version: '3.8'
services:
    server:
        user: 'node'
        build:
            context: .
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules
        command: npm start
        ports:
            - 3000:3000
